
service: snet-functions

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  service-name: handler
    warmup: true
    handler: handler
    role: ${file(./config.${self:provider.stage}.json):ROLE}